### ISSUE TITLE
Начисление баллов за совет коллеге (палец вверх)

### ISSUE THREAD

**Issue by Liliya-Stepanovna** [Broscorp-net/community-tools#158]
Trainee может оставлять коментарии к pr коллеги. Остальные пользователи могут на них реагировать.

* При получении **пальчик вверх** от автора pr добавить автору коментария один балл. (игнорировать лайки самого себя)
* При получении **пальчик вверх** от ментора добавить автору коментария два балла.
* При получении **пальчик вниз** от ментора отнять один балл у автора комента.

**Comment by likeRewca** [comment]
Так как ивенты с реакцией не приходят, я решил немного сделать по другому. 
В приходящих событиях я выслеживаю ивент "action": "labeled", после этого я смотрю на метку.
Если стоит метка "done", то вызываю метод из сервиса "Кармы", передаю параметр по которому буду искать в методе нужный нам пулл (пока сравниваю значение diff_url). 
В том методе я нахожу нужный пул, ищу коммент "approved" и забираю список реакций. И исходя из условий карма или уменьшается или увеличивается.

**Comment by likeRewca** [comment]
Сделал небольшие изменения выше написанного, теперь происходит поиск по номеру пулла, а не по значению diff_url.

**Comment by pesua** [comment]
@likeRewca т.е. карма начислится когда пулл примут? А если его не примут? Ты обсуждал это решение с продукт оунером?

**Comment by Liliya-Stepanovna** [comment]
@pesua да, решение было обосновано тем, что ребята могут хаотично писать друг другу комменты, аппрувить их и тем самым "зарабатывать" карму. Нам показалось более логичным сделать начисление кармы после принятия пулла, возможно, мы ошиблись..
